grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: 200
      max_depth: 3 
      learning_rate: 0.1
    search_param_grid:
      n_estimators : 
      - 200 
      max_depth : 
      - 3 
      learning_rate : 
      - 0.1

    